---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Style/MapToHash:
  Exclude:
  - lib/eac_fs/comparator/build.rb
Style/OptionalBooleanParameter:
  Exclude:
  - lib/eac_fs/storage_tree.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - lib/eac_fs/patches/module.rb
  - lib/eac_fs/patches/object.rb
  - lib/eac_fs/patches/pathname.rb
  - lib/eac_fs/patches.rb
  - spec/lib/eac_fs/storage_tree_spec.rb
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
